# Generated by Django 4.0 on 2021-12-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='none', max_length=20)),
                ('description', models.CharField(blank=True, default='none', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='none', max_length=20)),
                ('description', models.CharField(blank=True, default='none', max_length=200)),
                ('module_attache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produit.module')),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='none', max_length=20)),
                ('description', models.CharField(blank=True, default='none', max_length=200)),
                ('sequence_attache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produit.sequence')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='none', max_length=20)),
                ('sigle', models.CharField(blank=True, default='none', max_length=20)),
                ('intitule', models.CharField(blank=True, default='none', max_length=500)),
                ('milisime', models.CharField(blank=True, default='none', max_length=20)),
                ('grn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administration.grn')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='produit_attache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produit.produit'),
        ),
    ]
