# Generated by Django 4.0 on 2021-12-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='none', max_length=20, verbose_name='Code AFPA / stagiaire')),
                ('is_afpa', models.TextField(default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='none', max_length=20, verbose_name='Code offre')),
                ('date_debut', models.DateField(blank=True, default='none', max_length=12)),
                ('date_fin', models.DateField(blank=True, default='none', max_length=12)),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administration.centre')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOffre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default='none', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OffreProduit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('offre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commercial.offre')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produit.produit')),
            ],
        ),
        migrations.AddField(
            model_name='offre',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commercial.typeoffre'),
        ),
    ]
