# Generated by Django 4.0 on 2021-12-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produit', '0001_initial'),
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposeDe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('offre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commercial.offre')),
                ('seance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produit.seance')),
            ],
        ),
        migrations.CreateModel(
            name='Suivie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_stagiaire', models.DateField(verbose_name='Date début par le stagiaire')),
                ('demarrage_stagiaire', models.BooleanField(default=False, verbose_name='Démarrage par le stagiaire')),
                ('fin_stagiaire', models.DateField(verbose_name='Date Fin')),
                ('termine_stagiaire', models.BooleanField(default=False, verbose_name='Terminée par le stagiaire')),
                ('valide_stagiaire', models.BooleanField(default=False, verbose_name='Validée par le stagiaire')),
                ('valide_formateur', models.BooleanField(default=False, verbose_name='Validée par le formateur')),
                ('seance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedago.composede')),
            ],
        ),
    ]
