# Generated by Django 4.0.2 on 2022-02-09 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='none', max_length=20)),
                ('sigle', models.CharField(blank=True, default='none', max_length=20)),
                ('intitule', models.CharField(blank=True, default='none', max_length=500)),
                ('milisime', models.CharField(blank=True, default='none', max_length=20)),
                ('grn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administration.grn')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='none', max_length=20)),
                ('description', models.CharField(blank=True, default='none', max_length=200)),
                ('lab_attache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lab.lab')),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='none', max_length=20)),
                ('description', models.CharField(blank=True, default='none', max_length=200)),
                ('module_attache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lab.module')),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='none', max_length=20)),
                ('description', models.CharField(blank=True, default='none', max_length=200)),
                ('sequence_attache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lab.sequence')),
            ],
        ),
    ]
